// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace POLTest1.Tests.SettingsAPI
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Settings", SourceFile="Tests\\Settings API\\Settings.feature", SourceLine=0)]
    public partial class SettingsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Settings.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Settings", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("To Verify the GET request of Settings API using SettingsID", new string[] {
                "happypath"}, SourceLine=3)]
        public virtual void ToVerifyTheGETRequestOfSettingsAPIUsingSettingsID()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To Verify the GET request of Settings API using SettingsID", new string[] {
                        "happypath"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table143 = new TechTalk.SpecFlow.Table(new string[] {
                        "SettingsID"});
            table143.AddRow(new string[] {
                        "1520"});
#line 6
 testRunner.Given("Provided with the valid SettingsID.", ((string)(null)), table143, "Given ");
#line 9
 testRunner.When("I send a GET request to fetch settings details.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
  testRunner.Then("The valid settings details should be displayed.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("To Verify the Delete request of Settings API using SettingsID", new string[] {
                "happypath"}, SourceLine=12)]
        public virtual void ToVerifyTheDeleteRequestOfSettingsAPIUsingSettingsID()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To Verify the Delete request of Settings API using SettingsID", new string[] {
                        "happypath"});
#line 13
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table144 = new TechTalk.SpecFlow.Table(new string[] {
                        "SettingsID"});
            table144.AddRow(new string[] {
                        "1631"});
#line 15
 testRunner.Given("Provided with the valid SettingsID to be deleted.", ((string)(null)), table144, "Given ");
#line 18
 testRunner.When("I send a DELETE request to Delete settings details.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
 testRunner.Then("The settings details should be deleted.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("To Verify the POST request of Settings API", new string[] {
                "happypath"}, SourceLine=21)]
        public virtual void ToVerifyThePOSTRequestOfSettingsAPI()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To Verify the POST request of Settings API", new string[] {
                        "happypath"});
#line 22
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table145 = new TechTalk.SpecFlow.Table(new string[] {
                        "EntityId",
                        "EntityType",
                        "EntityText",
                        "Address",
                        "city",
                        "state",
                        "zip",
                        "UserId",
                        "ModifiedById"});
            table145.AddRow(new string[] {
                        "605499",
                        "1",
                        "Southern Elms",
                        "4519 E 31st  Street",
                        "Tulsa",
                        "OK",
                        "74135",
                        "0",
                        "0"});
#line 23
 testRunner.Given("I have provided Entity Settings details.", ((string)(null)), table145, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table146 = new TechTalk.SpecFlow.Table(new string[] {
                        "settingsID",
                        "settingType",
                        "settingValue"});
            table146.AddRow(new string[] {
                        "260",
                        "HO4",
                        "true"});
#line 26
 testRunner.And("Provided with the new SettingsInfo details.", ((string)(null)), table146, "And ");
#line 29
 testRunner.When("I send a POST request to add new settings", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("The valid settings details should be saved.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("To Verify the PUT request of Settings API", new string[] {
                "happypath"}, SourceLine=32)]
        public virtual void ToVerifyThePUTRequestOfSettingsAPI()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To Verify the PUT request of Settings API", new string[] {
                        "happypath"});
#line 33
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table147 = new TechTalk.SpecFlow.Table(new string[] {
                        "EntityId",
                        "EntityType",
                        "EntityText",
                        "Address",
                        "city",
                        "state",
                        "zip",
                        "UserId",
                        "ModifiedById"});
            table147.AddRow(new string[] {
                        "601234",
                        "1",
                        "BlueStone Lofts",
                        "101 Summit St",
                        "Duluth",
                        "CA",
                        "55803",
                        "-1",
                        "0"});
#line 34
 testRunner.Given("I have provided Entity Settings details for PUT Request.", ((string)(null)), table147, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table148 = new TechTalk.SpecFlow.Table(new string[] {
                        "settingsID",
                        "settingType",
                        "settingValue"});
            table148.AddRow(new string[] {
                        "291",
                        "POL",
                        "true"});
#line 37
 testRunner.And("Provided with the new SettingsInfo details for PUT.", ((string)(null)), table148, "And ");
#line 40
 testRunner.When("I send a PUT request to update new settings", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 41
 testRunner.Then("The valid settings details should be updated.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("To Verify the GET request of Settings API using EntityID and EntityType", new string[] {
                "happypath"}, SourceLine=43)]
        public virtual void ToVerifyTheGETRequestOfSettingsAPIUsingEntityIDAndEntityType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To Verify the GET request of Settings API using EntityID and EntityType", new string[] {
                        "happypath"});
#line 44
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table149 = new TechTalk.SpecFlow.Table(new string[] {
                        "EntityID",
                        "EntityType"});
            table149.AddRow(new string[] {
                        "9277",
                        "Property"});
#line 46
 testRunner.Given("Provided with the valid EntityID and EntityType.", ((string)(null)), table149, "Given ");
#line 50
 testRunner.When("I send a GET request to fetch settings details EntityID and EntityType.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 51
 testRunner.Then("The valid settings details should be displayed based on EntityID and EntityType.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("To Verify the GET request of Settings API using PropertyID and PropertyType", new string[] {
                "happypath"}, SourceLine=53)]
        public virtual void ToVerifyTheGETRequestOfSettingsAPIUsingPropertyIDAndPropertyType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To Verify the GET request of Settings API using PropertyID and PropertyType", new string[] {
                        "happypath"});
#line 54
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table150 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyID",
                        "PropertyType"});
            table150.AddRow(new string[] {
                        "609769",
                        "LeasingDesk"});
            table150.AddRow(new string[] {
                        "2913444",
                        "Onesite"});
            table150.AddRow(new string[] {
                        "6717648",
                        "Yardi"});
#line 56
 testRunner.Given("Provided with the valid PropertyID and PropertyType.", ((string)(null)), table150, "Given ");
#line 61
 testRunner.When("I send a GET request to fetch settings details PropertyID and PropertyType.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
 testRunner.Then("The valid settings details should be displayed based on PropertyID and PropertyTy" +
                    "pe.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
